/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Consultant from './Consultant';
import MunicipalityMimage from './MunicipalityMimage';

/**
 * The Candidate model module.
 * @module model/Candidate
 * @version 1.0.0
 */
class Candidate {
    /**
     * Constructs a new <code>Candidate</code>.
     * @alias module:model/Candidate
     * @param cname {String} 
     * @param cbio {String} 
     * @param cimage {module:model/MunicipalityMimage} 
     * @param cconsultants {Array.<module:model/Consultant>} 
     */
    constructor(cname, cbio, cimage, cconsultants) { 
        
        Candidate.initialize(this, cname, cbio, cimage, cconsultants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cname, cbio, cimage, cconsultants) { 
        obj['cname'] = cname;
        obj['cbio'] = cbio;
        obj['cimage'] = cimage;
        obj['cconsultants'] = cconsultants;
    }

    /**
     * Constructs a <code>Candidate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Candidate} obj Optional instance to populate.
     * @return {module:model/Candidate} The populated <code>Candidate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Candidate();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('cname')) {
                obj['cname'] = ApiClient.convertToType(data['cname'], 'String');
            }
            if (data.hasOwnProperty('cbio')) {
                obj['cbio'] = ApiClient.convertToType(data['cbio'], 'String');
            }
            if (data.hasOwnProperty('cimage')) {
                obj['cimage'] = MunicipalityMimage.constructFromObject(data['cimage']);
            }
            if (data.hasOwnProperty('cconsultants')) {
                obj['cconsultants'] = ApiClient.convertToType(data['cconsultants'], [Consultant]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Candidate.prototype['_id'] = undefined;

/**
 * @member {String} cname
 */
Candidate.prototype['cname'] = undefined;

/**
 * @member {String} cbio
 */
Candidate.prototype['cbio'] = undefined;

/**
 * @member {module:model/MunicipalityMimage} cimage
 */
Candidate.prototype['cimage'] = undefined;

/**
 * @member {Array.<module:model/Consultant>} cconsultants
 */
Candidate.prototype['cconsultants'] = undefined;






export default Candidate;

