/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MunicipalityMimage from './MunicipalityMimage';

/**
 * The Consultant model module.
 * @module model/Consultant
 * @version 1.0.0
 */
class Consultant {
    /**
     * Constructs a new <code>Consultant</code>.
     * @alias module:model/Consultant
     * @param consname {String} 
     * @param consimage {module:model/MunicipalityMimage} 
     * @param consbio {String} 
     */
    constructor(consname, consimage, consbio) { 
        
        Consultant.initialize(this, consname, consimage, consbio);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, consname, consimage, consbio) { 
        obj['consname'] = consname;
        obj['consimage'] = consimage;
        obj['consbio'] = consbio;
    }

    /**
     * Constructs a <code>Consultant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Consultant} obj Optional instance to populate.
     * @return {module:model/Consultant} The populated <code>Consultant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Consultant();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('consname')) {
                obj['consname'] = ApiClient.convertToType(data['consname'], 'String');
            }
            if (data.hasOwnProperty('consimage')) {
                obj['consimage'] = MunicipalityMimage.constructFromObject(data['consimage']);
            }
            if (data.hasOwnProperty('consbio')) {
                obj['consbio'] = ApiClient.convertToType(data['consbio'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Consultant.prototype['_id'] = undefined;

/**
 * @member {String} consname
 */
Consultant.prototype['consname'] = undefined;

/**
 * @member {module:model/MunicipalityMimage} consimage
 */
Consultant.prototype['consimage'] = undefined;

/**
 * @member {String} consbio
 */
Consultant.prototype['consbio'] = undefined;






export default Consultant;

