/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Candidate from './Candidate';
import MunicipalityMimage from './MunicipalityMimage';

/**
 * The Municipality model module.
 * @module model/Municipality
 * @version 1.0.0
 */
class Municipality {
    /**
     * Constructs a new <code>Municipality</code>.
     * @alias module:model/Municipality
     * @param mimage {module:model/MunicipalityMimage} 
     * @param mname {String} 
     * @param mcandidates {Array.<module:model/Candidate>} 
     */
    constructor(mimage, mname, mcandidates) { 
        
        Municipality.initialize(this, mimage, mname, mcandidates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mimage, mname, mcandidates) { 
        obj['mimage'] = mimage;
        obj['mname'] = mname;
        obj['mcandidates'] = mcandidates;
    }

    /**
     * Constructs a <code>Municipality</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Municipality} obj Optional instance to populate.
     * @return {module:model/Municipality} The populated <code>Municipality</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Municipality();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('mimage')) {
                obj['mimage'] = MunicipalityMimage.constructFromObject(data['mimage']);
            }
            if (data.hasOwnProperty('mname')) {
                obj['mname'] = ApiClient.convertToType(data['mname'], 'String');
            }
            if (data.hasOwnProperty('mcandidates')) {
                obj['mcandidates'] = ApiClient.convertToType(data['mcandidates'], [Candidate]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Municipality.prototype['_id'] = undefined;

/**
 * @member {module:model/MunicipalityMimage} mimage
 */
Municipality.prototype['mimage'] = undefined;

/**
 * @member {String} mname
 */
Municipality.prototype['mname'] = undefined;

/**
 * @member {Array.<module:model/Candidate>} mcandidates
 */
Municipality.prototype['mcandidates'] = undefined;






export default Municipality;

