/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Candidate from './model/Candidate';
import Consultant from './model/Consultant';
import Municipality from './model/Municipality';
import MunicipalityMimage from './model/MunicipalityMimage';
import CandidateApi from './api/CandidateApi';
import ConsultantApi from './api/ConsultantApi';
import MunicipalityApi from './api/MunicipalityApi';


/**
* This_is_a_sample_openApi_document.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TempApi = require('index'); // See note below*.
* var xxxSvc = new TempApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TempApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TempApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TempApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Candidate model constructor.
     * @property {module:model/Candidate}
     */
    Candidate,

    /**
     * The Consultant model constructor.
     * @property {module:model/Consultant}
     */
    Consultant,

    /**
     * The Municipality model constructor.
     * @property {module:model/Municipality}
     */
    Municipality,

    /**
     * The MunicipalityMimage model constructor.
     * @property {module:model/MunicipalityMimage}
     */
    MunicipalityMimage,

    /**
    * The CandidateApi service constructor.
    * @property {module:api/CandidateApi}
    */
    CandidateApi,

    /**
    * The ConsultantApi service constructor.
    * @property {module:api/ConsultantApi}
    */
    ConsultantApi,

    /**
    * The MunicipalityApi service constructor.
    * @property {module:api/MunicipalityApi}
    */
    MunicipalityApi
};

export default {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Candidate model constructor.
     * @property {module:model/Candidate}
     */
    Candidate,

    /**
     * The Consultant model constructor.
     * @property {module:model/Consultant}
     */
    Consultant,

    /**
     * The Municipality model constructor.
     * @property {module:model/Municipality}
     */
    Municipality,

    /**
     * The MunicipalityMimage model constructor.
     * @property {module:model/MunicipalityMimage}
     */
    MunicipalityMimage,

    /**
    * The CandidateApi service constructor.
    * @property {module:api/CandidateApi}
    */
    CandidateApi,

    /**
    * The ConsultantApi service constructor.
    * @property {module:api/ConsultantApi}
    */
    ConsultantApi,

    /**
    * The MunicipalityApi service constructor.
    * @property {module:api/MunicipalityApi}
    */
    MunicipalityApi
};
