/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.MunicipalityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MunicipalityApi', function() {
    describe('createmunicipality', function() {
      it('should call createmunicipality successfully', function(done) {
        //uncomment below and update the code to test createmunicipality
        //instance.createmunicipality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletemunicipality', function() {
      it('should call deletemunicipality successfully', function(done) {
        //uncomment below and update the code to test deletemunicipality
        //instance.deletemunicipality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllmunicipality', function() {
      it('should call getAllmunicipality successfully', function(done) {
        //uncomment below and update the code to test getAllmunicipality
        //instance.getAllmunicipality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getmunicipality', function() {
      it('should call getmunicipality successfully', function(done) {
        //uncomment below and update the code to test getmunicipality
        //instance.getmunicipality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatemunicipality', function() {
      it('should call updatemunicipality successfully', function(done) {
        //uncomment below and update the code to test updatemunicipality
        //instance.updatemunicipality(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
